---
- apt: pkg=python-psycopg2
- postgresql_db: name='{{item.pg_database}}'
                encoding='UTF-8'
                lc_collate='{{rails_pg_collocation}}'
                lc_ctype='{{rails_pg_collocation}}'
                template='template0'
                owner='{{item.user}}'
  with_items: apps
  when: item.pg_database is defined
  sudo_user: postgres

- postgresql_user: name='{{item.user}' role_attr_flags='SUPERUSER'
  with_items: apps
  when: item.pg_database is defined

- template: 'dest={{item.path}}/shared/config/database.yml src=database.yml.j2 owner={{item.user}}'
  with_items: apps
  when: item.pg_database is defined

- file: path=/backup/db state=directory recurse=true
- file: path=/backup/db/{{item.name}} state=directory recurse=true owner='{{item.user}}'
  with_items: apps
  when: item.pg_database is defined

- cron: name='backup {{item.name}}' hour='4' minute=0
        job="pg_dump -c {{item.pg_database}} | gzip > /backup/db/{{item.name}}/`date +\%F:\%T`.sql.gz && cd /backup/db/{{item.name}} && rm -f `ls -t | awk 'NR>7'`"
        user='{{item.user}}'
  with_items: apps
  when: item.pg_database is defined

